name: Upstream stable image

on:
  push:
    paths:
      - 'Dockerfile'
  workflow_dispatch:

jobs:
  build-and-push-release-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Extract build args
        id: keydb
        uses: pozetroninc/github-action-get-latest-release@v0.8.0
        with:
          owner: usememos
          repo: memos
          excludes: prerelease, draft
          token: ${{ github.token }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.token }}

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            ghcr.io/${{ github.repository }}
          tags: |
            type=raw,value=stable
            type=semver,pattern={{version}},value=${{ steps.keydb.outputs.release }}
            # type=semver,pattern={{major}}.{{minor}},value=${{ steps.keydb.outputs.release }}

      - name: Build and Push
        id: docker_build
        uses: docker/build-push-action@v6
        with:
          context: ./
          file: ./Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
